---
server:
  shutdown: graceful
  port: 8080

spring:
  main:
    allow-bean-definition-overriding: true
  jackson:
    default-property-inclusion: non_null
  data:
    mongodb:
      auto-index-creation: true
      uri: mongodb://admin:password@localhost:27017/db_kwebflux?authSource=admin
  cloud:
    function:
      definition: rabbitProducer, rabbitConsumer
    stream:
      binders:
        rabbit:
          type: 'rabbit'
        kafka:
          type: 'kafka'
      bindings:
        updateStarterProducer-out-0:
          binder: 'rabbit'
          destination: 'updateStarter-queue'
          content-type: 'application/json'
        updateStarterConsumer-in-0:
          binder: 'rabbit'
          group: 'updateStarter-group'
          destination: 'updateStarter-queue'
        updateLegendaryProducer-out-0:
          binder: 'kafka'
          destination: 'updateLegendary-topic'
          content-type: 'application/json'
        updateLegendaryConsumer-in-0:
          binder: 'kafka'
          group: 'updateLegendary-group'
          destination: 'updateLegendary-topic'

integration:
  client:
    default:
      timeout: 10000
      keep-idle: 1
      keep-interval: 1
      keep-cnt: 1
    pokemon-api:
      url: 'http://localhost:9080/api'
      timeout: 10000
